server:
  port: 8081
spring:
  cloud:
    open-feign:
      client:
        config:
          getNonWorkingDays:
            url: http://localhost:8080/api/non-working-days
            connect-timeout: 5000
            read-timeout: 5000
            errorDecoder: com.github.henrymorgan2.paymentschedulecalculator.cleint.RetryErrorDecoder
            retryer: com.github.henrymorgan2.paymentschedulecalculator.cleint.Retryer


  kafka:
    bootstrap-servers: localhost:9093

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

logging:
  level:
    root: DEBUG